# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=2)),
                ('no', models.IntegerField(verbose_name='number')),
                ('player', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('gs', models.IntegerField(default=0)),
                ('sb', models.IntegerField(default=0)),
                ('g', models.IntegerField(default=0)),
                ('sh', models.IntegerField(default=0)),
                ('sg', models.IntegerField(default=0)),
                ('a', models.IntegerField(default=0)),
                ('fc', models.IntegerField(default=0)),
                ('fs', models.IntegerField(default=0)),
                ('yc', models.IntegerField(default=0)),
                ('rc', models.IntegerField(default=0)),
            ],
        ),
    ]
